name: rf_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0
  - beautifulsoup4=4.13.4
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - catalogue=2.0.10
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.1.8
  - cloudpathlib=0.21.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - confection=0.1.5
  - cymem=2.0.11
  - cython=3.1.2
  - cython-blis=1.0.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - jinja2=3.1.6
  - langcodes=3.4.1
  - language-data=1.3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=20.1.7
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.29
  - libsqlite=3.50.1
  - libzlib=1.3.1
  - llvm-openmp=20.1.7
  - marisa-trie=1.2.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - murmurhash=1.0.10
  - ncurses=6.5
  - numpy=2.0.2
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.3.0
  - pip=25.1.1
  - preshed=3.0.9
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - readline=8.2
  - requests=2.32.4
  - rich=14.0.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - smart-open=7.1.0
  - smart_open=7.1.0
  - soupsieve=2.7
  - spacy=3.8.6
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.5.1
  - thinc=8.3.2
  - tk=8.6.13
  - tqdm=4.67.1
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - typing-extensions=4.14.0
  - typing-inspection=0.4.1
  - typing_extensions=4.14.0
  - tzdata=2025b
  - ujson=5.10.0
  - urllib3=2.5.0
  - wasabi=1.1.3
  - weasel=0.4.1
  - wheel=0.45.1
  - wrapt=1.17.2
  - zstandard=0.23.0
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - en-core-web-sm==3.8.0
      - es-core-news-sm==3.8.0
      - chromadb
      - langchain
      - langchain-core
      - langchain-text-splitters
      - langsmith
      - sentence-transformers
      - faiss-cpu
      - transformers
      - openai
